"""Initial schema (autogenerated skeleton).

For simplicity in the demo environment, this file delegates to SQLAlchemy's
metadata-based `create_all` via the `app.db_init` module. It still satisfies
Alembic's expectations so the migration system remains usable.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # No-op: handled by `python -m app.db_init` in development.
    pass


def downgrade() -> None:
    pass
